CREATE DATABASE CasasRurales 
ON
PRIMARY
(
NAME ='RURALMDF',
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVERBADAT\MSSQL\DATA\CASAS_RURALES\RURALMDF.MDF',
SIZE=3 MB,
MAXSIZE=40 MB,
FILEGROWTH=10%
)
LOG ON
(
NAME='RURALLDF',
FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVERBADAT\MSSQL\DATA\CASAS_RURALES\RURALLDF.LDF',
SIZE=10 MB,
MAXSIZE=UNLIMITED,
FILEGROWTH=10%
)