--EJERCICIO 1
SELECT * FROM EMPLEADOS
--2
SELECT * FROM DEPARTAMENTOS
--3
SELECT * FROM EMPLEADOS
WHERE CARGO = 'EMPLEADO'
--4
SELECT * FROM EMPLEADOS
WHERE CARGO = 'EMPLEADO'
ORDER BY NOMBRE
--5
SELECT NOMBRE, SALARIO FROM EMPLEADOS
--6
SELECT NOMBRE FROM DEPARTAMENTOS
--7
SELECT NOMBRE FROM DEPARTAMENTOS
ORDER BY NOMBRE 
--8 
SELECT NOMBRE FROM DEPARTAMENTOS
ORDER BY DEPT 
--9
SELECT NOMBRE FROM DEPARTAMENTOS
ORDER BY DEPT DESC
--10
SELECT NOMBRE, CARGO, SALARIO FROM EMPLEADOS 
ORDER BY SALARIO
--11
SELECT NOMBRE, CARGO, SALARIO FROM EMPLEADOS 
ORDER BY CARGO, SALARIO
--12
SELECT NOMBRE, CARGO, SALARIO FROM EMPLEADOS 
ORDER BY CARGO DESC
SELECT NOMBRE, CARGO, SALARIO FROM EMPLEADOS 
ORDER BY SALARIO
--13
SELECT SALARIO, COMISION FROM EMPLEADOS
WHERE DEPT = 30
--14
SELECT SALARIO, COMISION FROM EMPLEADOS
WHERE DEPT = 30
ORDER BY COMISION
--15
SELECT NOMBRE FROM EMPLEADOS
WHERE COMISION != 0
--16
SELECT SALARIO, COMISION FROM EMPLEADOS
WHERE CEMPL > 7500
--17
SELECT DISTINCT COMISION, DEPT 
FROM EMPLEADOS
--18
SELECT NOMBRE, (SALARIO + 1000) AS SALARIO2
FROM EMPLEADOS
WHERE DEPT = 20;
--19
SELECT NOMBRE, (SALARIO + 1000) AS IMPORTE
FROM EMPLEADOS
WHERE DEPT = 20;
--20
SELECT NOMBRE, SALARIO, COMISION FROM EMPLEADOS
WHERE COMISION > SALARIO / 2
--21
SELECT NOMBRE, SALARIO, COMISION FROM EMPLEADOS
WHERE COMISION <= SALARIO * 0.25
--22
SELECT 
    CONCAT('Nombre: ', NOMBRE) AS NOMBRE,
    CONCAT('Puesto: ', CARGO) AS PUESTO
FROM EMPLEADOS
WHERE COMISION <= (SALARIO * 0.25);
--23
SELECT NOMBRE
FROM EMPLEADOS
WHERE NOMBRE LIKE 'J%'
ORDER BY NOMBRE
--24
SELECT SALARIO, COMISION, (SALARIO + COMISION) AS IMPORTE, CEMPL
FROM EMPLEADOS
WHERE COMISION != 0
ORDER BY CEMPL
--25
SELECT NOMBRE, SALARIO, COMISION FROM EMPLEADOS
WHERE COMISION = 0
--26
SELECT NOMBRE FROM EMPLEADOS
WHERE JEFE = 7698 AND SALARIO > 1000
--27
SELECT NOMBRE, JEFE, SALARIO FROM EMPLEADOS
WHERE JEFE = 7698 AND SALARIO > 1000
--28
SELECT ((COMISION / SALARIO) * 100 ) AS PORCENTAJE, NOMBRE
FROM EMPLEADOS
WHERE COMISION != 0
ORDER BY NOMBRE
--29
SELECT NOMBRE FROM EMPLEADOS
WHERE NOMBRE NOT LIKE '%A%'
ORDER BY NOMBRE
--30
SELECT NOMBRE FROM EMPLEADOS
WHERE JEFE = CEMPL
--31
SELECT NOMBRE FROM DEPARTAMENTOS
WHERE NOMBRE != 'CONTABILIDAD' AND NOMBRE != 'COMERCIAL'
ORDER BY CIUDAD
--32
SELECT NOMBRE, DEPT FROM EMPLEADOS
WHERE NOMBRE = 'COMERCIAL' AND DEPT != 10 AND SALARIO > 1300
--33
SELECT NOMBRE FROM EMPLEADOS
WHERE NOMBRE LIKE '_____'
--34
SELECT NOMBRE FROM EMPLEADOS
WHERE LEN(NOMBRE) > 5
--35
SELECT NOMBRE FROM EMPLEADOS
WHERE (NOMBRE LIKE 'A%' AND SALARIO > 1000)
OR (COMISION != 0 AND DEPT = 20)
--36
SELECT NOMBRE FROM EMPLEADOS
WHERE SALARIO BETWEEN (COMISION / 2) AND COMISION
--37
SELECT NOMBRE,SALARIO,COMISION FROM EMPLEADOS
WHERE SALARIO BETWEEN (COMISION / 2) AND COMISION
--38
SELECT NOMBRE, (SALARIO + (SALARIO * 0.06)) AS SALARIOACTUAL, (SALARIO + (SALARIO * 0.07)) AS SALARIONUEVO
FROM EMPLEADOS
--39
SELECT NOMBRE, DEPT FROM EMPLEADOS
ORDER BY NOMBRE ASC, CEMPL DESC
--40
SELECT AVG(SALARIO) AS MEDIASALARIOS, COUNT(NOMBRE) AS NUMEMPLEADOS
FROM EMPLEADOS
--41
SELECT MAX(SALARIO) AS SALARIOMASALTO, SUM(COMISION) AS MEDIACOMISIONES, COUNT(NOMBRE) AS TOTALEMPLEADOS FROM EMPLEADOS
--42
SELECT NOMBRE, CEMPL, SALARIO, COMISION, DEPT
FROM EMPLEADOS
WHERE SALARIO > (SELECT SALARIO FROM EMPLEADOS WHERE CEMPL = 7934) 
ORDER BY SALARIO DESC
--43
SELECT NOMBRE FROM EMPLEADOS 
WHERE NOMBRE LIKE '_%'
ORDER BY NOMBRE DESC
--44
SELECT MIN(SALARIO) AS SALARIOMIN, MAX(SALARIO) AS SALARIOMAX, (MAX(SALARIO) - MIN(SALARIO)) AS DIFF FROM EMPLEADOS
--45
--SELECT NOMBRE FROM EMPLEADOS
--WHERE LEN(CIUDAD) > 5
--ORDER BY CIUDAD DESC, NOMBRE ASC
--46
SELECT COUNT(NOMBRE) AS EMPLEADOSCONCOMISION FROM EMPLEADOS
WHERE COMISION != 0 
--47
SELECT COUNT(NOMBRE) EMPLEADOSDEPT20 FROM EMPLEADOS
WHERE DEPT = 20
--48
SELECT NOMBRE FROM EMPLEADOS
WHERE DEPT = 30
ORDER BY COMISION DESC
--49
SELECT COUNT(NOMBRE) 
AS EMPLDEPT10 FROM EMPLEADOS WHERE DEPT = 10

--50
--SELECT DEPT FROM EMPLEADOS
--GROUP BY NOMBRE
--HAVING COUNT(NOMBRE) = 0 
--51
SELECT DEPT FROM EMPLEADOS
GROUP BY DEPT
HAVING COUNT(NOMBRE) > 3
--52

--53
--54
--55
--56
--57
--58
--59
--60
